# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e041d71dbe90781367f8df95f2b80aa883beafaa6ebe3c4a0523fd65c82cde8117d678e2e8e1f3b8e73357897253ecd888cd1de6c66c0a962863ddcf17c2a0c5

test:
  secret_key_base: 7f8f20c664a1749822182616634561e179c215344d4e6f35106d0dad59ee127b9709fbd2132ef7dd644246d282131afb446698299b7624e39d6b2e03c6f17f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
